### ISSUE TITLE
Is it working with 2.4 ?

### ISSUE THREAD

**Issue by eduardo-g-silva** [kiwicommerce/magento2-customer-password#15]
Hi have anybody try the module with 2.4 ?
Thanks

**Comment by aholovan** [comment]
@eduardo-g-silva 
seems it works on 2.4.1 but on 2.4.6 there is a compilation error
https://github.com/kiwicommerce/magento2-customer-password/issues/16
